services:
  # Redis Database
  redis:
    image: redis:7-alpine
    container_name: numerals-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - numerals-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: numerals-postgres
    environment:
      POSTGRES_DB: numerals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - numerals-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: numerals-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_TYPE: redis
      REDIS_URL: redis://redis:6379
      POSTGRES_URL: postgresql://postgres:password@postgres:5432/numerals
      RATE_LIMIT_MAX: 100
      RATE_LIMIT_TIME_WINDOW: 60000
      CORS_ORIGIN: http://localhost:5173,http://localhost:5174,http://localhost:3000
      LOG_LEVEL: info
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      start_period: 15s
      retries: 5
    networks:
      - numerals-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: numerals-frontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5174:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - numerals-network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  numerals-network:
    driver: bridge
